README.md
This PR fixes couple of typos in the README and improves some phrasing.
=> fix typos and improve some sentences

python/examples/servers/awaiting.py, python/examples/servers/echo.py, python/examples/servers/sync_echo.py, python/pyproject.toml, python/src/acp_sdk/server/__init__.py, python/src/acp_sdk/server/agent.py, python/src/acp_sdk/server/app.py, python/src/acp_sdk/server/bundle.py, python/src/acp_sdk/server/context.py, python/src/acp_sdk/server/server.py, python/src/acp_sdk/server/types.py, uv.lock
=> feat: improve agent interface

python/examples/servers/multi-echo.py, python/src/acp_sdk/server/__init__.py, python/src/acp_sdk/server/agent.py, python/src/acp_sdk/server/bundle.py, python/src/acp_sdk/server/context.py, python/src/acp_sdk/server/server.py
=> chore: simplify agent registration

python/examples/servers/multi-echo.py, python/src/acp_sdk/server/server.py
=> feat: make context param optional

.github/workflows/main.yml, python/pytest.ini, python/tests/conftest.py, python/tests/e2e/config.py, python/tests/e2e/fixtures/client.py, python/tests/e2e/fixtures/server.py, python/tests/e2e/test_suites/test_runs.py
=> chore(tests): improve structure

python/examples/servers/historian.py, python/src/acp_sdk/server/agent.py, python/src/acp_sdk/server/app.py, python/src/acp_sdk/server/bundle.py, python/src/acp_sdk/server/server.py
=> feat: improve session and metadata support

python/examples/clients/session.py, python/src/acp_sdk/client/client.py, python/tests/e2e/fixtures/server.py, python/tests/e2e/test_suites/test_runs.py
=> feat: add session support to client

python/README.md, python/examples/servers/standalone.py, python/src/acp_sdk/server/__init__.py, python/src/acp_sdk/server/agent.py, python/src/acp_sdk/server/server.py
=> feat: separate agent decorator from server

python/examples/clients/simple.py, python/examples/clients/stream.py, python/examples/servers/awaiting.py, python/src/acp_sdk/models/models.py, python/tests/e2e/fixtures/server.py, python/tests/e2e/test_suites/test_runs.py
- implement content-type-based structure of messages and artifacts
- add tests for the provided features
=> feat: implement message and artifact structure

python/src/acp_sdk/server/bundle.py, python/src/acp_sdk/server/types.py
=> fix: add support for yielding None value

python/examples/servers/awaiting.py, python/src/acp_sdk/models/models.py, python/src/acp_sdk/server/app.py, python/src/acp_sdk/server/bundle.py, python/src/acp_sdk/server/types.py, python/tests/e2e/fixtures/server.py, python/tests/e2e/test_suites/test_runs.py
=> feat: await message support

.github/workflows/main.yml, python/src/acp_sdk/models/models.py, python/tests/unit/models/test_models.py
=> feat: add message compression

examples/python/prompt-chaining/agent.py, examples/python/prompt-chaining/pyproject.toml, uv.lock
Implementation of prompt-chaining pattern based on https://www.anthropic.com/engineering/building-effective-agents
=> feat: prompt chaining pattern example

.github/workflows/docs.yml, docs/_sidebar.md, docs/index.html, python/docs/_sidebar.md, python/docs/client.md, python/docs/index.html, python/docs/models.md, python/docs/server.md
=> feat: add python sdk docs

examples/python/beeai-canvas/README.md, examples/python/beeai-canvas/agent.py, examples/python/beeai-canvas/client.py, examples/python/beeai-canvas/pyproject.toml, uv.lock
Example of creating files and writing programs, demonstrating how artifacts work in ACP.
Uses `gemma3:12b-it-qat` since that's the state-of-the-art model in this weight category.
=> feat(examples): add beeai-canvas

examples/python/crewai-song-writer/agent.py
=> fix(examples): re-create crewai agents on each run

python/pyproject.toml, python/src/acp_sdk/server/app.py, python/src/acp_sdk/server/server.py, python/tests/e2e/fixtures/server.py, python/tests/e2e/test_suites/test_runs.py, uv.lock
=> feat: add run ttl

examples/python/basic/await-external-approval/client.py, examples/python/basic/clients/advanced.py, examples/python/basic/clients/session.py, examples/python/basic/clients/simple.py, examples/python/basic/clients/stream.py, examples/python/beeai-canvas/client.py, examples/python/beeai-chat/client.py, examples/python/beeai-prompt-chaining/agent.py, examples/python/beeai-routing/translation_tool.py, examples/python/crewai-song-writer/client.py, examples/python/gpt-researcher/client_stream.py, examples/python/gpt-researcher/client_sync.py, examples/python/langgraph-greeting/client_stream.py, examples/python/langgraph-greeting/client_sync.py, python/pyproject.toml, python/src/acp_sdk/client/client.py, python/tests/e2e/test_suites/test_runs.py, python/tests/unit/client/test_client.py, uv.lock
Refs: https://github.com/i-am-bee/acp/issues/52
=> feat: extend allow input types on the client

python/src/acp_sdk/server/bundle.py, python/src/acp_sdk/server/types.py
=> feat: extends agent yield options

python/src/acp_sdk/client/client.py
=> feat: extend client ctor with all httpx params

README.md, docs/how-to/await-external-response.mdx, docs/how-to/compose-agents.mdx, docs/how-to/debug.mdx, docs/how-to/discover-and-run-agent.mdx, docs/introduction/quickstart.mdx, docs/python-sdk/client.mdx, docs/spec/openapi.yaml, examples/python/basic/await-external-approval/client.py, examples/python/basic/clients/session.py, examples/python/beeai-prompt-chaining/agent.py, examples/python/beeai-routing/translation_tool.py, examples/python/langgraph-greeting/client_sync.py, python/docs/client.md, python/src/acp_sdk/client/client.py, python/src/acp_sdk/models/models.py, python/src/acp_sdk/models/schemas.py, python/src/acp_sdk/server/app.py, python/src/acp_sdk/server/bundle.py, python/src/acp_sdk/server/session.py, python/tests/e2e/test_suites/test_runs.py, python/tests/unit/client/test_client.py
=> feat: make inputs and outputs singular on protocol level

docs/how-to/debug.mdx, docs/introduction/uv-primer.mdx
- unify method of creating new project with quickstart
- inline a footnote that wasn't showing up for some reason
=> docs: small fixes

docs/spec/openapi.yaml, python/src/acp_sdk/models/models.py
Closes https://github.com/i-am-bee/acp/issues/68
=> feat(agent-detail): update metadata

python/src/acp_sdk/models/models.py, python/tests/unit/models/test_models.py
=> fix: message concatenation

python/src/acp_sdk/client/client.py, python/src/acp_sdk/server/app.py, python/src/acp_sdk/server/session.py, python/tests/unit/client/test_client.py
=> fix: ignore external sessions

docs/spec/openapi.yaml, python/src/acp_sdk/models/models.py, python/src/acp_sdk/server/bundle.py, python/tests/unit/client/test_utils.py, python/tests/unit/models/test_models.py
=> feat: add timestamps to runs and messages

docs/spec/openapi.yaml, python/src/acp_sdk/client/client.py, python/src/acp_sdk/models/schemas.py, python/src/acp_sdk/server/app.py, python/tests/e2e/test_suites/test_discovery.py
=> feat: add ping endpoint

docs/spec/openapi.yaml, python/src/acp_sdk/client/client.py, python/src/acp_sdk/models/schemas.py, python/src/acp_sdk/server/app.py, python/src/acp_sdk/server/bundle.py, python/tests/e2e/test_suites/test_runs.py, python/tests/unit/client/test_client.py
=> feat: add events endpoint

python/src/acp_sdk/models/models.py, python/src/acp_sdk/server/agent.py, python/src/acp_sdk/server/types.py, python/tests/e2e/fixtures/server.py, python/tests/e2e/test_suites/test_runs.py, python/tests/unit/models/test_models.py
=> fix: agent cancellation

python/src/acp_sdk/server/bundle.py, python/tests/e2e/fixtures/server.py, python/tests/e2e/test_suites/test_runs.py
=> fix: exception yield and task cancellation safeguard

docs/introduction/example-agents.mdx
Documentation updates for the issue #105 .
=> docs: update to example-agents list

examples/python/acp-agent-generator/.env.example, examples/python/acp-agent-generator/README.md, examples/python/acp-agent-generator/agent.py, examples/python/acp-agent-generator/client.py, examples/python/acp-agent-generator/mcpdoctool.py, examples/python/acp-agent-generator/pyproject.toml, uv.lock
This an example using LLM + llms.txt to generate a ACP server plus agent.
[106](https://github.com/i-am-bee/acp/issues/106)
=> feature(examples): Build ACP agent generator 

examples/python/acp-agent-generator/.env.example, examples/python/acp-agent-generator/README.md, examples/python/acp-agent-generator/agent.py, examples/python/acp-agent-generator/mcpdoctool.py
better perf by binding tools and adding system prompt (gpt-4o-mini still not stable)
add pydantic settings
=> feature(example): update acp agent generator

docs/introduction/example-agents.mdx
Updating docs for #123 example
=> docs(examples): updating examples page with OpenAI Agent

docs/package-lock.json
=> fix: license

README.md, typescript/README.md
=> chore(typescript): update readme

docs/spec/agents-get.mdx, docs/spec/agents-list.mdx, docs/spec/openapi.yaml, docs/spec/ping.mdx, docs/spec/run-cancel.mdx, docs/spec/run-create.mdx, docs/spec/run-get-events.mdx, docs/spec/run-get.mdx, docs/spec/run-resume.mdx
**Key improvements:**
- Fix `AgentsListResponse` to reference `agents` (not `events`)
- Add `summary` fields, update `description` fields
- Add pattern for `AgentName` and specify min/max length per **RFC 1123**
- Make `Error` response reusable with `$ref`
=> feat(spec): improve validation, consistency

README.md, docs/core-concepts/message-structure.mdx, docs/how-to/compose-agents.mdx, docs/how-to/discover-and-run-agent.mdx, docs/introduction/example-agents.mdx, docs/introduction/quickstart.mdx, docs/spec/openapi.yaml, examples/python/acp-agent-generator/client.py, examples/python/basic/clients/distributed-session.py, examples/python/basic/clients/session.py, examples/python/beeai-canvas/agent.py, examples/python/beeai-canvas/client.py, examples/python/beeai-chat/agent.py, examples/python/beeai-chat/client.py, examples/python/beeai-handoff/agent.py
Refs https://github.com/i-am-bee/acp/issues/141
=> docs: update docs and examples with message role

.github/workflows/main.yml, docs/package-lock.json, docs/package.json
Signed-off-by: Tomas Pilar <tomas.pilar@ibm.com>
=> chore(docs): add schema validation pipeline

python/src/acp_sdk/client/client.py, python/tests/e2e/test_suites/test_sessions.py, python/tests/unit/client/test_client.py
Signed-off-by: Tomas Pilar <tomas.pilar@ibm.com>
=> fix(python): multiple session clients

docs/how-to/high-availability.mdx, examples/python/basic/servers/store.py
Signed-off-by: Tomas Pilar <tomas.pilar@ibm.com>
=> fix(docs): high availability howto

python/src/acp_sdk/server/app.py, python/src/acp_sdk/server/server.py
Signed-off-by: Tomas Pilar <thomas7pilar@gmail.com>
=> feat(python): add base url configuration to forwarded resources

python/src/acp_sdk/client/client.py
- This is a potential fix for [issue 222](https://github.com/i-am-bee/acp/issues/222).
- Successfully ran all unit tests.
- Successfully ran all E2E tests.
=> fix (python client): Potential fix for issue 222
